# Generated by Django 4.2.4 on 2023-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(default='01-01-2023', verbose_name='дата создания'),
        ),
    ]
