# Generated by Django 4.2.4 on 2023-09-16 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 14, 47, 12, 727503), verbose_name='дата создания'),
        ),
    ]
