# Generated by Django 4.2.4 on 2023-09-16 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
    ]
